// Generated by CoffeeScript 1.6.1
(function() {
  var Hand, Ohs, Player, Utils;

  Player = (function() {

    function Player(name) {
      this.name = name;
      this.hands = [];
      this.totalScore = 0;
    }

    return Player;

  })();

  /* --------------------------------------------
       Begin Hand.coffee
  --------------------------------------------
  */


  Hand = (function() {

    function Hand(bid) {
      this.bid = bid;
    }

    return Hand;

  })();

  /* --------------------------------------------
       Begin Utils.coffee
  --------------------------------------------
  */


  Utils = {
    maxArray: function(array) {
      return Math.max.apply(null, array);
    },
    trimCheck: function() {
      if (!String.prototype.trim) {
        String.prototype.trim = function() {
          return this.replace(/^\s+|\s+$/g, '');
        };
        return true;
      }
    }
  };

  /* --------------------------------------------
       Begin ohell.coffee
  --------------------------------------------
  */


  /*
  * @fileOverview Handles all functionality for executing the Oh Hell Scoresheet
  * web application that allows the user to track the scores of everyone during a
  * game of Oh Hell.
  * Dependencies: jQuery, Handlebars
  * @author David Wilhelm
  * @version 2.3.9
  */


  Ohs = {
    init: function() {
      this.cacheVariables();
      this.bindNewGame();
      return Utils.trimCheck();
    },
    cacheVariables: function() {
      this.$namesFormTemplate = Handlebars.compile($('#namesFormTemplate').html());
      this.$biddingFormTemplate = Handlebars.compile($('#biddingFormTemplate').html());
      this.$correctBidsFormTemplate = Handlebars.compile($('#correctBidsFormTemplate').html());
      this.$scoreBoardTemplate = Handlebars.compile($('#scoreBoardTemplate').html());
      this.$newGameBtn = $('#newGameBtn');
      this.$container = $('#container');
      this.$numPlayersSection = $('#numPlayersSection');
      this.gameStarted = false;
      this.game = [];
      this.settings = {};
      this.$newGameBtn.button();
      return true;
    },
    bindNewGame: function() {
      this.$newGameBtn.on('click', this.startNewGame);
      return this.$numPlayersSection.find('button').on('click', this.setNumPlayers);
    },
    startNewGame: function() {
      if (!Ohs.gameStarted) {
        Ohs.gameStarted = true;
      } else {
        Ohs.game = [];
        Ohs.settings = {};
      }
      return Ohs.$numPlayersSection.slideDown().removeClass('hide');
    },
    setNumPlayers: function() {
      var p;
      Ohs.settings.numPlayers = parseInt($('#numPlayers').val(), 10);
      p = Ohs.settings.numPlayers;
      Ohs.settings.maxNumCards = p <= 5 ? 10 : Math.floor(52 / p);
      return Ohs.renderNamesForm();
    },
    renderNamesForm: function() {
      var num, players;
      this.$numPlayersSection.slideUp().addClass('hide');
      players = {
        count: (function() {
          var _i, _ref, _results;
          _results = [];
          for (num = _i = 1, _ref = this.settings.numPlayers; 1 <= _ref ? _i <= _ref : _i >= _ref; num = 1 <= _ref ? ++_i : --_i) {
            _results.push(num);
          }
          return _results;
        }).call(this)
      };
      this.$container.append(this.$namesFormTemplate(players));
      return $('#nameForm').on('submit', this.setPlayerNames).slideDown().removeClass('hide');
    },
    setPlayerNames: function(e) {
      var index, name, names, _i, _len;
      e.preventDefault();
      names = $(this).serializeArray();
      for (index = _i = 0, _len = names.length; _i < _len; index = ++_i) {
        name = names[index];
        if (!name.value) {
          name.value = "Player " + (index + 1);
        }
        Ohs.game.push(new Player(name.value.trim()));
      }
      $(this).slideUp(400, function() {
        return $(this).remove();
      });
      return Ohs.renderScoringForm();
    },
    renderScoringForm: function() {
      return $('#scoringForm').on('submit', this.setScoringParams).slideDown().removeClass('hide');
    },
    setScoringParams: function(e) {
      var bidVal, h, num, params, trickVal, _i, _j, _ref, _ref1;
      e.preventDefault();
      params = $(this).serializeArray();
      if (parseInt(params[0].value, 10) === 0) {
        h = (function() {
          var _i, _ref, _results;
          _results = [];
          for (num = _i = 1, _ref = Ohs.settings.maxNumCards; 1 <= _ref ? _i <= _ref : _i >= _ref; num = 1 <= _ref ? ++_i : --_i) {
            _results.push(num);
          }
          return _results;
        })();
        for (num = _i = _ref = Ohs.settings.maxNumCards - 1; _ref <= 1 ? _i <= 1 : _i >= 1; num = _ref <= 1 ? ++_i : --_i) {
          h.push(num);
        }
      } else {
        h = (function() {
          var _j, _ref1, _results;
          _results = [];
          for (num = _j = _ref1 = Ohs.settings.maxNumCards; _ref1 <= 1 ? _j <= 1 : _j >= 1; num = _ref1 <= 1 ? ++_j : --_j) {
            _results.push(num);
          }
          return _results;
        })();
        for (num = _j = 2, _ref1 = Ohs.settings.maxNumCards; 2 <= _ref1 ? _j <= _ref1 : _j >= _ref1; num = 2 <= _ref1 ? ++_j : --_j) {
          h.push(num);
        }
      }
      Ohs.settings.handSizeOrder = h;
      trickVal = parseInt(params[1].value, 10);
      Ohs.settings.trickValue = trickVal ? trickVal : 1;
      bidVal = parseInt(params[2].value, 10);
      Ohs.settings.correctBidValue = bidVal ? bidVal : 5;
      $(this).slideUp(400, function() {
        return $(this).addClass('hide');
      });
      return Ohs.renderBiddingForm();
    },
    renderBiddingForm: function() {
      var data, num;
      data = {
        players: this.game,
        handNum: this.game[0].hands.length + 1
      };
      data.numCards = this.settings.handSizeOrder[data.handNum - 1];
      data.count = (function() {
        var _i, _ref, _results;
        _results = [];
        for (num = _i = 0, _ref = data.numCards; 0 <= _ref ? _i <= _ref : _i >= _ref; num = 0 <= _ref ? ++_i : --_i) {
          _results.push(num);
        }
        return _results;
      })();
      data.numCards += data.numCards > 1 ? ' cards' : ' card';
      this.$container.append(this.$biddingFormTemplate(data));
      return $('#biddingForm').on('submit', this.setPlayerBids).slideDown().removeClass('hide').next().find('button').on('click', this.renderCorrectBidsForm);
    },
    setPlayerBids: function(e) {
      var bid, bids, player, _i, _j, _len, _len1, _ref;
      e.preventDefault();
      bids = $(this).serializeArray();
      _ref = Ohs.game;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        player = _ref[_i];
        for (_j = 0, _len1 = bids.length; _j < _len1; _j++) {
          bid = bids[_j];
          if (player.name === bid.name) {
            player.hands.push(new Hand(bid.value));
          }
        }
      }
      return $(this).slideUp(300, function() {
        return $(this).next().slideDown().removeClass('hide').end().remove();
      });
    },
    renderCorrectBidsForm: function() {
      var data, i, p, player, _i, _len, _ref;
      data = {
        players: []
      };
      i = Ohs.game[0].hands.length - 1;
      _ref = Ohs.game;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        player = _ref[_i];
        p = {
          name: player.name,
          bid: player.hands[i].bid
        };
        p.bid += p.bid === 1 ? ' trick' : ' tricks';
        data.players.push(p);
      }
      Ohs.$container.append(Ohs.$correctBidsFormTemplate(data));
      $(this).parent().slideUp(400, function() {
        return $(this).remove();
      });
      return $('#correctBidsForm').on('submit', Ohs.calcBids).slideDown().removeClass('hide');
    },
    calcBids: function() {
      var results;
      results = $(this).serializeArray();
      return true;
    },
    renderScoreBoard: function(e) {
      var scores;
      e.preventDefault();
      scores = {
        players: Ohs.game
      };
      return $(this).slideUp(600, function() {
        return $(this).next().slideDown().removeClass('hide').end().remove();
      });
    }
  };

  Ohs.init();

}).call(this);
